baseURL = "/"
languageCode = "en-us"
title = "JmsDnns"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

disableKinds = ["sitemap"]

[taxonomies]
series = "series"
[outputs]
section = ['html', 'rss']

[pagination]
pagerSize = 3

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
google_analytics_id = ""
showAuthorOnHomepage = false
showAuthorOnPosts = false
showPostsOnHomepage = false
addDot = true
addFrame = false
highlightColor = '#5294e2'
baseColor = "#ffffff"
baseOffsetColor = "#eaeaea"
headingColor = "#000000"
textColor = "#4e5157"
dotColor = "#5294e2"
darkBaseColor = "#16171a"
darkBaseOffsetColor = "#2d2d2d"
darkHeadingColor = "#ffffff"
darkTextColor = "#c9c9c9"
darkHighlightColor = "#5294e2"
darkDotColor = "#5294e2"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[deployment]

[[deployment.targets]]
name = "live"
URL = "s3://jmsdnns.com?region=us-east-1"
cloudFrontDistributionID = "E28NFOMHCWR2CR"
